"""Add publer_account_ids to clients

Revision ID: b377d3f5d4af
Revises: 764054baedb3
Create Date: 2025-11-03 23:16:35.587583+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b377d3f5d4af'
down_revision = '764054baedb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('publer_account_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'publer_account_ids')
    # ### end Alembic commands ###
